"""empty message

Revision ID: 16e77c5d0211
Revises: 323dedd2797a
Create Date: 2020-07-24 17:11:11.889750

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '16e77c5d0211'
down_revision = '323dedd2797a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('addr', sa.String(length=5000), nullable=True))
    op.add_column('cards', sa.Column('company', sa.String(length=500), nullable=True))
    op.add_column('cards', sa.Column('department', sa.String(length=500), nullable=True))
    op.add_column('cards', sa.Column('email', sa.String(length=500), nullable=True))
    op.add_column('cards', sa.Column('is_analysis', sa.Boolean(), nullable=True))
    op.add_column('cards', sa.Column('name', sa.String(length=1000), nullable=True))
    op.add_column('cards', sa.Column('original_factory', sa.String(length=500), nullable=True))
    op.add_column('cards', sa.Column('own', sa.Integer(), nullable=True))
    op.add_column('cards', sa.Column('remarks', sa.String(length=5000), nullable=True))
    op.add_column('cards', sa.Column('tel_cell', sa.String(length=500), nullable=True))
    op.add_column('cards', sa.Column('tel_work', sa.String(length=500), nullable=True))
    op.add_column('cards', sa.Column('title', sa.String(length=500), nullable=True))
    op.drop_column('cards', 'is_ok')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('is_ok', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('cards', 'title')
    op.drop_column('cards', 'tel_work')
    op.drop_column('cards', 'tel_cell')
    op.drop_column('cards', 'remarks')
    op.drop_column('cards', 'own')
    op.drop_column('cards', 'original_factory')
    op.drop_column('cards', 'name')
    op.drop_column('cards', 'is_analysis')
    op.drop_column('cards', 'email')
    op.drop_column('cards', 'department')
    op.drop_column('cards', 'company')
    op.drop_column('cards', 'addr')
    # ### end Alembic commands ###
