"""empty message

Revision ID: 2312497a17d9
Revises: 16e77c5d0211
Create Date: 2020-07-24 17:27:21.265537

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2312497a17d9'
down_revision = '16e77c5d0211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'addr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('addr', mysql.VARCHAR(length=5000), nullable=True))
    # ### end Alembic commands ###
