"""empty message

Revision ID: 323dedd2797a
Revises: 3ede3460464e
Create Date: 2020-07-24 16:52:31.995565

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '323dedd2797a'
down_revision = '3ede3460464e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='roles')
    op.drop_table('roles')
    op.drop_column('cards', 'intent')
    op.drop_column('cards', 'company_url')
    op.drop_column('cards', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('date', mysql.TEXT(), nullable=True))
    op.add_column('cards', sa.Column('company_url', mysql.TEXT(), nullable=True))
    op.add_column('cards', sa.Column('intent', mysql.TEXT(), nullable=True))
    op.create_table('roles',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='roles_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'roles', ['name'], unique=True)
    # ### end Alembic commands ###
