"""empty message

Revision ID: 4f9a85ee8b70
Revises: b8f08fe23cd5
Create Date: 2020-07-21 15:35:31.179501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f9a85ee8b70'
down_revision = 'b8f08fe23cd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('company_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'company_url')
    # ### end Alembic commands ###
