"""empty message

Revision ID: d2918e6b2ba4
Revises: 2312497a17d9
Create Date: 2020-08-05 10:47:24.298404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2918e6b2ba4'
down_revision = '2312497a17d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('addr', sa.String(length=5000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'addr')
    # ### end Alembic commands ###
